### ISSUE TITLE
Magmatic boiler not restart push steam

### ISSUE THREAD

**Issue by VladimirMangos** [ChiefArug/ThermalSysteams#6] opened 2023-02-26 12:54 UTC
Let have pair magmatic boiler and steam engine.

When steam engine stop at full RF storage and not accept more steam then boiler fill own steam storage and stop
This is ok. But boiler not restart send steam to steam engine when steam engine restart work and can accept steam.

Hack fix required dismount boiler and place back

**Comment by VladimirMangos** [comment] 2023-02-27 12:29
In systeams-1.2.2.jar problem not solved

**Comment by VladimirMangos** [comment] 2023-02-28 15:14
I see commit https://github.com/ChiefArug/ThermalSysteams/commit/2a5e4ea567b881829dec1d342c90bc7605043e25
So look like this way work is intended possible. But in normal balanced energy system full energy storage and by chain standby generator and full steam storage is normal state. So make use steam boilers is hard in this ways.... (

**Comment by ChiefArug** [comment] 2023-02-28 21:54
Technically this is intended, it works the same way as dynamos.
Except dynamos will void some of their energy at the start of their tick cycle if they have fuel and their energy storage is full, so there is always room for more energy. However boilers don't void steam like that (intentionally).

I think this should be fixable by having it try export steam before it starts processing, if the output tank is full.

**Comment by VladimirMangos** [comment] 2023-02-28 22:24
But problem in not sending some steam to connected engine. Boiler have steam full and connected to steam engine with empty steam storage/
But steam nit go from boiler storage to engine fuel storage.

In case magmatic engien rf go from engine to power network independent from state engine.

**Comment by redninja555** [comment] 2023-03-01 00:52
I think I've also ran into this problem. As stated Boilers won't push steam into tanks if they see that their tank is full.

 A fix for 1.2.2, now that pipes can attach properly, is to just use pipes that have the ability to pull from the boiler such as mekanism mechanical pipes or fluiducts with a servo, or thermal series fluid cells set to auto input. These can pull steam out of the boiler and it will resume working as intended.

**Comment by ChiefArug** [comment] 2023-03-01 02:19
Fixed in https://github.com/ChiefArug/ThermalSysteams/commit/b9f7426ff917a910cafc45d4db2e686fd22c2a33

**Comment by ChiefArug** [comment] 2023-03-06 03:57
Fixed in https://www.curseforge.com/minecraft/mc-mods/systeams/files/4424099

**Closed by ChiefArug** 2023-03-06 03:57 UTC
